services:
  app:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_NAME=dogsdb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
      - DATABASE_HOST=192.168.42.81
    networks:
      - express-app

networks:
  express-app: