services:

  mysql:
    image: mysql:latest
    ports:
        - 3307:3306
    volumes:
        - /etc/localtime:/etc/localtime:ro
        - /etc/timezone:/etc/timezone:ro
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=1234
        - MYSQL_DATABASE=dogsdb
        - TZ=America/Argentina/Mendoza
    networks:
      - express-app

  app:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DATABASE_NAME=dogsdb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=1234
      - DATABASE_PORT=3306
      - DATABASE_HOST=mysql
      - CORS_ORIGIN=http://127.0.0.1
    networks:
      - express-app

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - express_app
      - react_app
    restart: always
    networks:
      - app_network


networks:
  express-app: